services:
  - type: web
    name: digital-surveyor-backend
    runtime: python
    rootDir: DigitalSurveyor_Backend
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port 10000
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.12
      - key: PIP_NO_CACHE_DIR
        value: "1"
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_SERVICE_ROLE_KEY
        sync: false
